# Generated by Django 5.0.2 on 2024-03-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=22)),
                ('password', models.CharField(max_length=22)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finishedTasks', models.IntegerField(default=0)),
            ],
        ),
    ]
