# Generated by Django 5.0.2 on 2024-04-25 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
